language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: 
        - mkdir -p /var/tmp/incremental-store/test/backups
        - mkdir /var/tmp/incremental-test
        - mkdir /var/tmp/incremental-store/test/backups/`date +%Y%m%d --date="yesterday"`
        - mkdir /var/tmp/incremental-store/test/backups/old
        - ln -s /var/tmp/incremental-store/test/backups/`date +%Y%m%d --date="yesterday"` /var/tmp/incremental-store/test/backups/latest
        - touch -d "365 days ago" /var/tmp/incremental-store/test/backups/old
        - python ./incremental.py -c ./incremental.def.yaml
