language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: 
        - mkdir -p /var/tmp/incremental-store/test/backups
        - mkdir /var/tmp/incremental-test
        - mkdir -p /var/tmp/incremental-store/test/backups/`date +%Y%m%d --date="yesterday"`/tree
        - mkdir -p /var/tmp/incremental-store/test/backups/`date +%Y%m%d --date="31 days ago"`/tree
        - ln -s /var/tmp/incremental-store/test/backups/`date +%Y%m%d --date="yesterday"` /var/tmp/incremental-store/test/backups/latest
        - date +%s --date="31 days ago" > /var/tmp/incremental-store/test/backups/`date +%Y%m%d --date="31 days ago"`/backup.done
        - python ./incremental.py -c ./incremental.def.yaml
        - python ./expire.py -c ./incremental.def.yaml
